# Clean environment for applying Ansible roles - with systemd inside
# Docker Hub: potyarkin/molecule:debian-10-systemd
FROM debian:10-slim
RUN \
    apt-get update && \
    apt-get install -y \
        sudo \
        python3 \
        && \
    apt-get clean
RUN apt-get update && \
    apt-get install -y \
        systemd \
        && \
    apt-get clean
