# Clean environment for applying Ansible roles
# Docker Hub: potyarkin/molecule:debian12
FROM debian:bookworm-slim
RUN \
    apt-get update && \
    apt-get install -y \
        sudo \
        python3 \
        lsb-release \
        && \
    apt-get clean
