# Docker image that will be the host for Molecule test runs
# Docker Hub: potyarkin/molecule:host
FROM debian:10-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        coreutils \
        curl \
        docker.io \
        gcc \
        libc-dev \
        libffi-dev \
        libssl-dev \
        make \
        python3-dev \
        python3-venv \
        && \
    apt-get clean
