# Clean environment for applying Ansible roles
# Docker Hub: potyarkin/molecule:debian-10
FROM debian:10-slim
RUN \
    apt-get update && \
    apt-get install -y \
        sudo \
        python3 \
        && \
    apt-get clean
