# Docker image that will be the host for Molecule test runs
# Docker Hub: potyarkin/molecule:host
FROM docker:latest
RUN apk add --no-cache \
        coreutils \
        curl \
        gcc \
        libffi-dev \
        make \
        musl-dev \
        openssl-dev \
        python3 \
        python3-dev
