# Clean environment for applying Ansible roles - with systemd inside
# Docker Hub: potyarkin/molecule:debian12-systemd
FROM debian:bookworm-slim
RUN \
    apt-get update && \
    apt-get install -y \
        sudo \
        python3 \
        lsb-release \
        systemd \
        && \
    ln -s /lib/systemd/systemd /sbin/init && \
    apt-get clean
