# Clean environment for applying Ansible roles - with systemd inside
# Docker Hub: potyarkin/molecule:debian11-systemd
FROM debian:bullseye-slim
RUN \
    apt-get update && \
    apt-get install -y \
        sudo \
        python3 \
        && \
    apt-get clean
RUN apt-get update && \
    apt-get install -y \
        systemd \
        && \
    ln -s /lib/systemd/systemd /sbin/init && \
    apt-get clean
