#
# Source this file from your ~/.bashrc
#


# COMMON variable must contain the proper path to the shared config directory,
# unless the files are placed into default location (~/common).
test -z "$COMMON" && COMMON="$HOME/common"


# This function can be used to reload settings within running bash session
_load_shell_settings() {
    local SOURCES  # paths relative to $COMMON
    SOURCES=(
        "cli-tools/bash_prompt"
        "cli-tools/bash_aliases"
        "cli-tools/bash_env"
        "cli-tools/bash_showupdates"
        "cli-tools/bash_dircolors"
        "cli-tools/bash_tmout"
    )

    if [ -d "$COMMON" ]
    then
        for ITEM in "${SOURCES[@]}"
        do
            source "$COMMON/$ITEM"
        done
    else
        echo "ERROR: \$COMMON is not a directory: $COMMON"
        return 1
    fi
}
_load_shell_settings
