# Invoke by adding `source bash_aliases` to ~/.bashrc


# Improved file listing
alias la='ls -A'
alias ll='ls -l'
alias ls='ls -F -h --color=auto --show-control-chars'

# Colored grep whenever possible
alias grep='grep --color=auto'

# Strip comments from file and print it to stdout
alias bones="grep -Ev '^\s*#'"

# Pretty print files to stdout, add filename headers
alias show="tail -v -n+1"

# Show file listing when changing current directory
_cd() {
    local CMD="builtin cd"
    local DEST
    if [ "$#" -eq 0 ]
    then
        set -- "$HOME"  # set default argument value for function
    fi
    $CMD "$@" && ls
}
alias cd=_cd
complete -d cd  # autocomplete only directories
complete -d _cd

# Pretty diff like `git diff`
_diff() {
    command diff --color=always "$@" | less -rXF
}
alias diff=_diff

# Make directory and cd into it
mkcd() {
    [ ! -d "$1" ] && mkdir -p "$1"
    cd "$1"
}

# Touch file and create required parent directories
# https://stackoverflow.com/a/19288855/3275560
mktouch() {
    for f in "$@"; do
        mkdir -p -- "$(dirname -- "$f")"
        touch -- "$f"
    done
}
