# Add these lines to the end of ~/.bashrc

COMMON="$HOME/common"

source "$COMMON/cli-tools/bash_prompt"
source "$COMMON/cli-tools/bash_aliases"
source "$COMMON/cli-tools/bash_env"
source "$COMMON/cli-tools/bash_showupdates"
source "$COMMON/cli-tools/bash_dircolors"
