#
# Source this file from your ~/.bashrc
#


# COMMON variable must contain the proper path to the shared config directory,
# unless the files are placed into default location (~/.common).
test -z "$COMMON" && COMMON="$HOME/.common"
export COMMON


# This function can be used to reload settings within running bash session
_load_shell_settings() {
    local ITEM
    local SOURCES
    local PREFIX="/dotfiles/bash/"
    SOURCES=(
        "prompt"
        "aliases"
        "env"
        "showupdates"
        "dircolors"
        "tmout"
        "interactive"
        "completion"
    )

    if [[ -d "$COMMON" && $- == *i* ]]
    then
        for ITEM in "${SOURCES[@]}"
        do
            source "$COMMON$PREFIX/$ITEM"  # source is bash builtin, POSIX standard is .
        done
    elif [[ -d "$COMMON" ]]
    then
        # Load only environment variables in non-interactive mode
        source "$COMMON$PREFIX/env"
    else
        echo "ERROR: \$COMMON is not a directory: $COMMON" &>2
        return 1
    fi
}
_load_shell_settings
