#
# Source this file from your ~/.bashrc
#


# COMMON variable must contain the proper path to the shared config directory,
# unless the files are placed into default location (~/.common).
test -z "$COMMON" && COMMON="$HOME/.common"
export COMMON


# All interactive shell sessions should be recorded
_record() {
    [[ $- == *i* && -t 0 && -n "$SESSION_SCROLLBACK_RECORD" ]] && return 0
    local dir="$HOME/.history.scrollback/$(date --utc +%Y%m)"
    mkdir --parents --mode=0700 "$dir"
    export SESSION_SCROLLBACK_RECORD="$(mktemp -qu "$dir/$(date --utc +%Y%m%d-%H%M)-XXXXX")"
    exec script \
        --append \
        --flush \
        --quiet \
        --return \
        --timing="$SESSION_SCROLLBACK_RECORD.time" \
        "$SESSION_SCROLLBACK_RECORD.scrollback"
}
# FIXME: Recording is currently disabled because it messes up tmux variables:
#        pane_current_command, pane_current_path (I use these variables a lot).
#        Tmux reads these variables from process group leader (with a fallback
#        to session leader in some cases): see format.c, osdep-linux.c in Tmux
#        sources.
#_record


# This function can be used to reload settings within running bash session
_load_shell_settings() {
    local ITEM
    local SOURCES
    local PREFIX="/dotfiles/bash/"
    SOURCES=(
        "prompt"
        "aliases"
        "env"
        "showupdates"
        "dircolors"
        "tmout"
        "interactive"
        "completion"
    )

    if [[ -d "$COMMON" && $- == *i* ]]
    then
        for ITEM in "${SOURCES[@]}"
        do
            source "$COMMON$PREFIX/$ITEM"  # source is bash builtin, POSIX standard is .
        done
    elif [[ -d "$COMMON" ]]
    then
        # Load only environment variables in non-interactive mode
        source "$COMMON$PREFIX/env"
    else
        echo "ERROR: \$COMMON is not a directory: $COMMON" &>2
        return 1
    fi
}
_load_shell_settings
